workflows:
  android-debug-build:
    name: Build AppCloner Debug APK (مضمون التثبيت)

    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"

    scripts:
      - name: Grant permissions
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug \
            --warning-mode none \
            --console=plain

    artifacts:
      # المسار الصحيح لنسخة الديباج
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - alywm100@gmail.com
