# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
# تم زيادة الذاكرة من 512m إلى 2048m لحل مشكلة نفاد الذاكرة
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تشغيل البناء المتوازي لتسريع العملية
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Namespacing of R class
android.nonTransitiveRClass=true

# تعطيل وضع R8 الكامل لتقليل استهلاك الذاكرة أثناء البناء
android.enableR8.fullMode=false

# سطر إضافي ضروري لمنع توقف البناء بسبب إدارات الـ SDK على الهاتف
android.suppressUnsupportedCompileSdk=35